- name: Fetch file from remote server to local
  fetch:
    src: "/{{  ansible_user }}/.ssh/authorized_keys"  
    dest: "./{{ base_path }}/{{ hostvars[inventory_hostname].region }}+{{ hostvars[inventory_hostname].scope }}+{{ inventory_hostname }}"
    flat: yes         

# - name: Fetch file from remote server to local
#   debug:
#     src: "/{{  ansible_user }}/.ssh/authorized_keys"  
#     dest: "./{{ base_path }}/{{ hostvars[inventory_hostname].region }}+{{ hostvars[inventory_hostname].scope }}+{{ inventory_hostname }}"
#     flat: yes             

- name: copy python script to local "ssh_folder"
  ansible.builtin.template:
    src: "data-pipeline.py"
    dest: "./{{ base_path }}/data-pipeline.py"
    mode: 0744
  delegate_to: localhost
  run_once: true
  become: false

- name: copy .ignore script to local "ssh_folder"
  ansible.builtin.template:
    src: ".ignore"
    dest: "./{{ base_path }}/.ignore"
    mode: 0744
  delegate_to: localhost
  run_once: true
  become: false